### ISSUE TITLE
Numérotation des résultats

### ISSUE THREAD

**Issue by R-Alexandre** [R-Alexandre/ClassesTex#15]
# À présent

Quand on a un bloc définition/théorème/proposition/lemme/etc. on a une numérotation de type 3.5 où 3 est le numéro de la section et 5 le numéro du bloc dans cette section.

# Le problème

Quand on change de chapitre, je n'arrive pas à trouver la commande pour faire référence à un tel résultat en indiquant le chapitre dans la référence (mais pas à tous les coups !). Par exemple, avoir au choix : I.3.5 ou 3.5

# Ce que j'aimerais

J'aimerai avoir simultanément :

- une numérotation des résultats avec uniquement le numéro du résultat dans la section (exemple : "Lemme 5" et plus "Lemme 3.5") ;
- un moyen de faire référence qui soit "intelligent" : quand on est dans la même section il n'affiche que le numéro du résultat, quand on change de section il rajoute la section et quand on change de chapitre il ajoute aussi le numéro du chapitre.

**Comment by Teguad** [comment]
Je me suis renseigné et je ne crois pas que ce ne soit possible de différencier les compteurs des théorèmes et ceux associés aux références.

Le mieux est de mettre le numéro des chapitres à tous les théorèmes. Personnellement, je trouve ça plus pratique pour s'y repérer après.

Cependant, essaye à tout hasard de demander sur un forum comme TeX StackExchange. ;-)

**Comment by R-Alexandre** [comment]
> Le mieux est de mettre le numéro des chapitres à tous les théorèmes. Personnellement, je trouve ça plus pratique pour s'y repérer après.

C'est-à-dire ?

**Comment by Teguad** [comment]
Je pensais à mettre les compteurs des théorèmes comme I.1.1. Au moins, tu as le numéro de chapitre dans les références mais aussi dans les théorèmes.

Et puis, je trouve ça plus facile pour retrouver des théorèmes. Tu n'aurais pas besoin de chercher le chapitre puis le bon numéro du théorème.

**Comment by R-Alexandre** [comment]
Mais ça chargerait beaucoup trop la présentation. Déjà que j'ai envie de ne plus afficher la section, je ne vais pas rajouter le chapitre ^^

**Comment by Teguad** [comment]
Ah oui, c'est sûr que ça la chargerait.

Pourquoi ne pas faire une numérotation continue ? C'est-à-dire de ne pas réinitialiser la numérotation à chaque section.

Ou alors, indiquer la page de la référence avec `\pageref{}` ?

**Comment by R-Alexandre** [comment]
Le problème d'une numérotation continue est qu'on arriverait trop rapidement sur des nombres très grand (genre 50) et c'est pas très élégant.

Humm, c'est une idée. Est-ce qu'on peut faire une commande unique qui peut décider s'il faut, ou non, afficher le numéro de la page (selon qu'on soit sur la même page ou pas) ?

**Comment by Teguad** [comment]
Euh oui, ça doit être possible. Je verrais ça se soir. ;-)

**Comment by Teguad** [comment]
Me revoilà ! J'ai fait un petite commande qui fait ce que tu veux. Elle s'utilise comme cela.
```latex
\documentclass{livre}

\titre{Test}

\begin{document}

\chapter{Test}

\definition{\label{un} Test}{}
\definition{\label{deux} Test}{}

\thmref{un}

\thmref{quatre}

\chapter{Test}

\definition{\label{trois} Test}{}
\definition{\label{quatre} Test}{}

\thmref{un}

\thmref{quatre}

\end{document}
```
Et donne ce [résultat](https://github.com/R-Alexandre/ClassesTex/files/198228/Test.pdf). Ça te convient ?

Par contre, ça fonctionne mal s'il y a des pages en romain.

**Comment by R-Alexandre** [comment]
Je préfèrerais quelque chose comme (4, p. 5) avec "p" en italique. C'est possible ?

**Comment by Teguad** [comment]
Bien-sûr ! [Voilà](https://github.com/R-Alexandre/ClassesTex/files/198328/Test.pdf) ! Si ça te vas, je fais une PR.

**Comment by R-Alexandre** [comment]
Tu ne peux pas mettre les parenthèses quand il y a le numéro de la page?

**Comment by Teguad** [comment]
Ah si, désolé... [Test](https://github.com/R-Alexandre/ClassesTex/files/198353/Test.pdf)

**Comment by R-Alexandre** [comment]
Parfait :)
