### ISSUE TITLE
Espace pour notes de bas de page

### ISSUE THREAD

**Issue by R-Alexandre** [R-Alexandre/ClassesTex#17]
Actuellement, on voit que la largeur du pied de page est plus importante que la largeur du texte ... est-ce que ça peut être corrigé ?

De plus, j'aimerais bien avoir quelque chose d'adapté au format A5 (ce qui pourrait faire figure de nouvelle option au passage ...).

**Comment by Teguad** [comment]
Pareil, je ne vois pas de problème.

Sinon, pour le A5, tu peux essayer de modifier l'option `tablette` dans les premières lignes de la classe.
```latex
\PassOptionsToPackage{
		top=1.5cm, bottom=0cm, left=1cm, right=1cm,
		headheight=\baselineskip, headsep=2em, footskip=4em
	}{geometry}
	\PassOptionsToClass{a5paper}{book}
```

**Comment by R-Alexandre** [comment]
Je sais pas si tu as fait des test, mais la marge de droite pour le corps de texte et pour les notes de bas de page ne sont pas les mêmes. Du coup on a l'impression que les notes de bas de page "débordent".

**Comment by Teguad** [comment]
Ah ui, j'avais eu le même problème pour un de mes documents. Met ça quelque part.
```latex
\headwidth\textwidth
```

**Comment by R-Alexandre** [comment]
Hum, ça ne marche pas à tous les coups. Par exemple page 2 ça va mais pas page 4.

[cours.pdf](https://github.com/R-Alexandre/ClassesTex/files/192229/cours.pdf)

**Comment by R-Alexandre** [comment]
En fait je vois même pas les cas où ça corrige le bug. Peut-être que je place mal cette commande ... où est-ce que je devrais la mettre?

**Comment by Teguad** [comment]
J'ai regardé vite fait et c'est un problème de césure en fait. Bizarrement, même en rajoutant un `\-` pour forcer, ça ne marche pas. Je vais regarder ça de plus près.

**Comment by Teguad** [comment]
Salut !

J'ai réussi à régler le problème. En fait, ça venait du faite que tu voulais que les notes ne se séparent pas sur plusieurs pages. Du coup, la boîte les contraignant à rester n'étaient pas de la même largeur. J'ai mis pas mal de temps à trouver que c'était à cause de ça. :-)

Par contre, j'ai des petits problème au niveau de Git, sur la fusion des branches. Je vais essayer de corriger ça de mon côté et te faire une PR.

**Comment by R-Alexandre** [comment]
Génial ! Merci :D

**Comment by Teguad** [comment]
Oh merde, je viens de me rendre compte que mon commit est allé sur la dernière PR #21 que tu n'avais pas accepté. Si tu veux, accepte-là et je te supprimerai les changements que tu ne veux pas.

**Comment by R-Alexandre** [comment]
Normalement, c'est bien corrigé :-)
