### ISSUE TITLE
Numérotation des pages

### ISSUE THREAD

**Issue by R-Alexandre** [R-Alexandre/ClassesTex#18]
Actuellement, la numérotation des pages suit assez mal la répartition gauche/droite.

De plus, j'aimerais bien pouvoir (i.e. avec une commande/option) insérer deux pages blanches après le titre (ce qui permet à l'impression d'avoir une coupure).

**Comment by R-Alexandre** [comment]
Rectification : juste une page blanche.

**Comment by Teguad** [comment]
C'est quoi le problème avec la répartition les numéros de page ? Je n'en vois pas. :-/

Sinon, tu peux utiliser la commande suivant pour insérer deux pages.
```latex
\newcommand{\doublepage}{%
	\clearpage
	\null\thispagestyle{empty} % Pas de numéro de page sur la page blanche.
	\setcounter{page}{0} % On met la page 1 après la page blanche.
	\clearpage
}
```

**Comment by R-Alexandre** [comment]
En fait, le jour où je vais imprimer mon cours, sur la première feuille j'aurai sur le recto la page de garde et sur le verso la table des matières, mais j'aurai voulu une coupure entre les deux.

**Comment by Teguad** [comment]
Bein, en utilisant la commande, ça te fait bien une coupure où tu veux non ?

**Comment by R-Alexandre** [comment]
J'ai pas testé mais merci pour le patch, j'imagine que ça convient parfaitement ;)

Je voulais juste t'expliquer le problème dans le cas où tu aurais pas saisi
