### ISSUE TITLE
Page de garde

### ISSUE THREAD

**Issue by R-Alexandre** [R-Alexandre/ClassesTex#3]
La page de garde est à revoir.

Une première piste : 
[modèle1.pdf](https://github.com/R-Alexandre/ClassesTex/files/120860/modele1.pdf)

*Tous* les éléments devraient être optionnels (**sauf** le titre).

Pour la taille de la police et l'alignement exact, c'est à retravailler au fur et à mesure :-).

**Comment by Teguad** [comment]
Rien de compliqué alors. Pour la police, tout est en gras ? Le titre doit être en majuscule ?

Je verrai ça demain.

**Comment by R-Alexandre** [comment]
Non, il faudrait ajuster ça. Certainement que le titre sera en capitales. Pour le reste faut tester ...

**Comment by Teguad** [comment]
Voici un premier [aperçu](https://github.com/R-Alexandre/ClassesTex/files/121477/Page_de_garde.pdf). Est-ce que ça va ?

Le code associé est le suivant.

```latex
\documentclass{livre}

\titre{Titre}
\soustitre{Sous-titre}
\auteurs{Auteurs}
\illustration{\includegraphics[width=5cm]{Illustration}}
\date{\today}
\lieu{Lieu}
\intervenants{Intervenants}
\rapporteurs{Rapporteurs}
\encadrants{Encadrants}

\begin{document}

\end{document}
```

**Comment by R-Alexandre** [comment]
C'est pas mal du tout ! Est-ce que tu peux remonter un peu la partie titre, sous-titre et auteurs ainsi que réduire un peu l'écart entre le sous-titre et les auteurs ?

**Comment by Teguad** [comment]
[Voilà !](https://github.com/R-Alexandre/ClassesTex/files/121512/Page_de_garde.pdf)

**Comment by R-Alexandre** [comment]
Parfait ! Je te laisse faire une PR
