### ISSUE TITLE
Bibliographie

### ISSUE THREAD

**Issue by R-Alexandre** [R-Alexandre/ClassesTex#7]
Je n'arrive plus à mettre de bibliographie ...

J'arrive bien à faire marcher biber mais après j'ai l'impression que le .bbl n'est pas utilisé (à la compilation pdflatex suivante) ...

Source : [Archive.zip](https://github.com/R-Alexandre/ClassesTex/files/121602/Archive.zip)

Help ?

**Comment by Teguad** [comment]
Dans ta chaîne de compilation, lances-tu bien `biber` ? Je l'ai fait en ligne de commande et ça fonctionne (`biber memoire.bcf`).

**Comment by R-Alexandre** [comment]
Oui j’ai bien lancé biber …
Sinon j’ai un Warning (ça vient peut-être de là) : 

Package biblatex Warning: File 'memoire.bbl' is wrong format version - expected 2.3.

J’ai tous mes paquets à jour (d’après TeXLive)

**Comment by Teguad** [comment]
Si tu le lances en ligne de commande, ça te donne quoi ?

**Comment by R-Alexandre** [comment]
C’est ce que je fais.

**Comment by R-Alexandre** [comment]
Est-ce que tu aurais d'autres pistes @Teguad ?

**Comment by Teguad** [comment]
Non, désolé, je n'ai pas avancé sur la question. C'est un problème d'installation du logiciel et, sur Mac OS X, je ne m'y connais pas trop.

**Comment by R-Alexandre** [comment]
Problème résolu, il s'avère que j'avais une ancienne version du paquet dans mon dossier où je mets mes propres classes et ça rentrait en conflit.
